create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists app_sessions_user_id_idx
  on public.app_sessions (user_id);

create index if not exists app_sessions_expires_at_idx
  on public.app_sessions (expires_at desc);

alter table public.distribution_items
  alter column inventory_item_id drop not null;

alter table public.distribution_items
  drop constraint if exists distribution_items_inventory_item_id_fkey;

alter table public.distribution_items
  add constraint distribution_items_inventory_item_id_fkey
  foreign key (inventory_item_id)
  references public.inventory_items(id)
  on delete set null;
