create table if not exists public.distribution_items (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null unique references public.inventory_items(id) on delete cascade,
  nama text not null,
  jumlah integer not null check (jumlah > 0),
  status text not null check (status in ('Gudang', 'Distribusi')),
  expired_at date not null,
  source_location text not null default 'Gudang Utama',
  queue_status text not null default 'Menunggu Distribusi',
  distributed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists distribution_items_distributed_at_idx
  on public.distribution_items (distributed_at desc);

create index if not exists distribution_items_status_idx
  on public.distribution_items (status);
